version: "3.5"

networks:
  # Create an explicit network so we can connect to it from the client to do deployments.
  # Create it externally so when we remove individual nodes it doesn't try to destroy it.
  casperlabs:
    external: true

volumes:
  socketvolume: {}

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: casperlabs-node/node-rs:${CL_VERSION}
    container_name: node-rs-${NODE_NUMBER}
    hostname: node-rs-${NODE_NUMBER}
    ports:
      # Port for root node
      - 34553:34553
      # bind port
      - 40403:40403
    volumes:
      # # config and chainspec
      # - $PWD/resources/local/config.toml:/root/resources/local/config.toml
      # - $PWD/resources/local/chainspec.toml:/root/resources/local/chainspec.toml
      # Node keys
      - $PWD/resources/local/secret_keys/node-1.pem:/root/casperlabs-node/resources/local/secret_keys/node-1.pem
    networks:
      - casperlabs
    environment:
      HOME: /root
      ROOT_ADDR: node-rs-0:34553
    env_file:
      - .env
    entrypoint:
      - sh
      - -c
      - RUST_BACKTRACE=full RUST_LOG=debug casperlabs-node validator -c=/root/casperlabs-node/resources/local/config.toml
